eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.122:8761/eureka/
  instance:
    ip-address: 192.168.0.122
    prefer-ip-address: true
